# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySystemReportPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма пополнения')),
                ('date_of_refill', models.DateField(auto_now_add=True, verbose_name='Дата пополнения')),
                ('time_of_refill', models.TimeField(auto_now_add=True, verbose_name='Время пополнения')),
                ('before_balance', models.CharField(default='', max_length=255, verbose_name='Баланс до')),
                ('after_balance', models.CharField(default='', max_length=255, verbose_name='Баланс после')),
                ('before_date_off', models.CharField(default='', max_length=255, verbose_name='Дата отключения до пополнения')),
                ('id_admin_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_system_report_pays', to='pythonix_admin.PaySystemAccessData', verbose_name='Выбор платежной системы')),
            ],
            options={
                'verbose_name': 'Пополнение платежной системой',
                'verbose_name_plural': 'Пополнения платежными системами',
                'db_table': 'report_pay_pay_systems',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 2, 19, 47, 16, 730743), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 9, 2, 19, 47, 16, 734718), verbose_name='Дата удаления временного платежа'),
        ),
        migrations.AddField(
            model_name='paysystemreportpay',
            name='id_client_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonix_admin.Clients', verbose_name='Выбор Клиента'),
        ),
    ]
