# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0002_auto_20170830_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredActionsWithClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('off', 'Отключить'), ('on', 'Включить')], max_length=255)),
            ],
            options={
                'verbose_name': 'Отложенное действие с клиентом',
                'verbose_name_plural': 'Отложенные действия с клиентами',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 2, 21, 17, 33, 462213), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='pysystemtransaction',
            name='login',
            field=models.CharField(default='', max_length=255, verbose_name='логин'),
        ),
        migrations.AlterField(
            model_name='pysystemtransaction',
            name='select_pay_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_system_transactions', to='pythonix_admin.PaySystemAccessData', verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='pysystemtransaction',
            name='sum',
            field=models.CharField(default='', max_length=255, verbose_name='Сумма транзакции'),
        ),
        migrations.AlterField(
            model_name='pysystemtransaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='pysystemtransaction',
            name='transaction_number',
            field=models.IntegerField(verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='pysystemtransaction',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время транзакции'),
        ),
        migrations.AlterField(
            model_name='sendemailadmin',
            name='event',
            field=models.CharField(choices=[('new_month', 'new_month'), ('clients_off', 'clients_off'), ('celery_on', 'celery_on'), ('payment', 'payment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 9, 2, 21, 17, 33, 467074), verbose_name='Дата удаления временного платежа'),
        ),
        migrations.AddField(
            model_name='deferredactionswithclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonix_admin.Clients'),
        ),
    ]
