# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0003_auto_20170830_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название устройства')),
                ('device_type', models.CharField(choices=[('bdcom', 'MikroTik RouterOS')], default=1, max_length=255, verbose_name='Выбор типа устройства')),
                ('network_address', models.GenericIPAddressField(verbose_name='Сетевой адрес устройства')),
                ('login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин для доступа к устройству')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль для доступа к устройству')),
                ('api_port', models.IntegerField(blank=True, null=True, verbose_name='API порт')),
                ('status_on_off', models.BooleanField(default=True, verbose_name='Состояние работы устройства')),
                ('radius_used', models.BooleanField(default=False, verbose_name='Использование радиус сервера')),
                ('snmp_public_community', models.CharField(max_length=255, verbose_name='Публичное сообщество SNMP')),
                ('snmp_private_community', models.CharField(max_length=255, verbose_name='Приватное сообщество SNMP')),
                ('physical_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switching_devices', to='pythonix_admin.PhysicalNetwork', verbose_name='Выбор физической сети')),
            ],
            options={
                'db_table': 'switching_device',
                'verbose_name_plural': 'Коммутационные устройства',
                'verbose_name': 'Коммутационное устройство',
            },
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 12, 12, 11, 57, 726421), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 12, 12, 11, 57, 742095), verbose_name='Дата удаления временного платежа'),
        ),
    ]
