# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0004_auto_20171009_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 12, 12, 14, 28, 737280), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='switchingdevice',
            name='device_type',
            field=models.CharField(choices=[('bdcom', 'BDCOM')], default=1, max_length=255, verbose_name='Выбор типа устройства'),
        ),
        migrations.AlterField(
            model_name='switchingdevice',
            name='snmp_private_community',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Приватное сообщество SNMP'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 12, 12, 14, 28, 752400), verbose_name='Дата удаления временного платежа'),
        ),
    ]
