# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0005_auto_20171009_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='onu_mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 13, 9, 34, 37, 837086), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 13, 9, 34, 37, 843225), verbose_name='Дата удаления временного платежа'),
        ),
    ]
