# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0006_auto_20171010_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemailadmin',
            options={'verbose_name': 'Администратор подписаный на уведомления', 'verbose_name_plural': 'Администраторы подписаные на уведомления'},
        ),
        migrations.AlterModelOptions(
            name='temporarypay',
            options={'verbose_name': 'Временный платеж', 'verbose_name_plural': 'Временные платежи'},
        ),
        migrations.AddField(
            model_name='tarifs',
            name='fix_work_period',
            field=models.BooleanField(default=True, verbose_name='Работает с первого по первое'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 20, 9, 0, 49, 915941), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True, verbose_name='МАС адрес клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='onu_mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True, verbose_name='МАС адрес ONU'),
        ),
        migrations.AlterField(
            model_name='deferredactionswithclient',
            name='action',
            field=models.CharField(choices=[('off', 'Отключить'), ('on', 'Включить'), ('del', 'Удалить'), ('create', 'Создать'), ('del', 'Удалить')], max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 20, 9, 0, 49, 932030), verbose_name='Дата удаления временного платежа'),
        ),
    ]
