# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0007_auto_20171017_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchingdevice',
            name='ssh_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='SSH порт'),
        ),
        migrations.AddField(
            model_name='switchingdevice',
            name='telnet_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telnet порт'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 20, 13, 56, 9, 399266), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='fix_work_period',
            field=models.BooleanField(default=False, verbose_name='Работает с первого по первое'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 20, 13, 56, 9, 404892), verbose_name='Дата удаления временного платежа'),
        ),
    ]
