# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0008_auto_20171017_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchingdevice',
            name='max_numbers_onu_to_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное колличество ONU на порт'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 21, 9, 7, 13, 271466), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 21, 9, 7, 13, 279386), verbose_name='Дата удаления временного платежа'),
        ),
    ]
