# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0009_auto_20171018_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferredactionswithclient',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deferredactionswithclient',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deferredactionswithclient',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 21, 10, 11, 0, 492963), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='deferredactionswithclient',
            name='action',
            field=models.CharField(choices=[('off', 'Отключить'), ('on', 'Включить'), ('create', 'Создать'), ('del', 'Удалить')], max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 10, 21, 10, 11, 0, 498475), verbose_name='Дата удаления временного платежа'),
        ),
    ]
