# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-22 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonix_admin', '0012_auto_20171031_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='end_used_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 12, 51, 53, 166345), verbose_name='Дата окончяния услуги'),
        ),
        migrations.AlterField(
            model_name='temporarypay',
            name='del_pay',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 12, 51, 53, 170593), verbose_name='Дата удаления временного платежа'),
        ),
    ]
